services:
  - type: web
    name: census-api
    env: python
    buildCommand: pip install -r starter/requirements.txt
    startCommand: |
  	echo "START COMMAND RUNNING"
  	PYTHONPATH=".:starter" uvicorn starter.main:app --host 0.0.0.0 --port 10000
    autoDeploy: true
